Initializes an empty project that builds
Infomaniak/android-rich-html-editor pull request #1
Opened 2024-05-31 12:18 UTC by LunarX

the init of an empty project has been split to its own PR

2024-05-31 12:36 UTC, KevinBoulongne requested changes

2024-05-31 12:36 UTC, KevinBoulongne commented on .gitignore
> +.DS_Store
Add the `*.aab` next to the `*.apk`.

2024-05-31 12:41 UTC, KevinBoulongne requested changes

2024-05-31 12:41 UTC, KevinBoulongne commented on rich-html-editor/src/main/AndroidManifest.xml
> +</manifest>
This one is empty, isn't there so default stuff ?

Or everything in it will be in the _"real"_ PR ?

2024-05-31 12:41 UTC, KevinBoulongne commented on sample/src/main/res/xml/backup_rules.xml
> +</full-backup-content>
Do we need this file ?

2024-05-31 12:41 UTC, KevinBoulongne commented on sample/src/main/res/xml/data_extraction_rules.xml
> +</data-extraction-rules>
Do we need this file ?

2024-05-31 12:41 UTC, KevinBoulongne commented on sample/src/main/res/xml/network_security_config.xml
> +</network-security-config>
Do we need this file ?

2024-05-31 12:41 UTC, KevinBoulongne commented on sample/src/test/java/com/infomaniak/lib/richhtmleditor/ExampleUnitTest.kt
> +}
Do we want tests in the sample ?

2024-05-31 12:41 UTC, KevinBoulongne commented on sample/src/androidTest/java/com/infomaniak/lib/richhtmleditor/ExampleInstrumentedTest.kt
> +}
Do we want tests in the sample ?

2024-05-31 12:44 UTC, KevinBoulongne commented
Missing CI files :
- android.yml
- auto-author-assign.yml
- dependent-issues.yml
- rebase-default-branch.yml

2024-05-31 13:04 UTC, LunarX commented on rich-html-editor/src/main/AndroidManifest.xml
> +</manifest>
Yeah no, after some testing if the manifest is empty it doesn't seem to be needed. And it stays empty even in the *real* PR

2024-05-31 13:16 UTC, LunarX commented on sample/src/main/res/xml/backup_rules.xml
> +</full-backup-content>
Yeah no, that one doesn't seem to be required when there's nothing to backup anyway

2024-05-31 13:16 UTC, LunarX commented on sample/src/main/res/xml/data_extraction_rules.xml
> +</data-extraction-rules>
That one seems to be required even if we disable the backup

2024-05-31 13:18 UTC, LunarX commented on sample/src/main/res/xml/network_security_config.xml
> +</network-security-config>
That one seems to be needed if we want to enable internet access to the WebView later on. This is a bit early but the initial project already acomodates for this

2024-06-03 07:06 UTC, LunarX commented on sample/src/test/java/com/infomaniak/lib/richhtmleditor/ExampleUnitTest.kt
> +}
Yeah, I removed them

2024-06-03 07:06 UTC, LunarX commented on sample/src/androidTest/java/com/infomaniak/lib/richhtmleditor/ExampleInstrumentedTest.kt
> +}
Yeah, I removed them

2024-06-03 12:34 UTC, KevinBoulongne approved these changes

2024-06-04 09:24 UTC, sirambd requested changes

2024-06-04 09:24 UTC, sirambd commented on sample/build.gradle.kts
> +        minSdk = 25
Why 25 ?

2024-06-04 09:24 UTC, sirambd commented on sample/build.gradle.kts
> +    implementation(project(":rich-html-editor"))
Move to first line of this block

2024-06-04 10:37 UTC, LunarX commented on sample/build.gradle.kts
> +        minSdk = 25
I tested it with the next PR and it works well with a minSdk of 21, so I made them both the same value for coherence

2024-06-04 11:59 UTC, tevincent requested changes

2024-06-04 11:59 UTC, tevincent commented on sample/.gitignore
> +/build
```
*.iml
.gradle
/local.properties
/.idea
.DS_Store
build/
/captures
.externalNativeBuild
.cxx
local.properties
*.apk
*.aab
```

2024-06-04 11:59 UTC, tevincent commented on rich-html-editor/build.gradle.kts
> +        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
Is that necessary ? Since you don't have any tests.

2024-06-05 07:19 UTC, LunarX commented on sample/.gitignore
> +/build
Are these not already caught by the main .gitignore? Wouldn't this be redundant?

2024-06-05 07:20 UTC, LunarX commented on sample/.gitignore
> +/build
The real question could be, do we even need to `/build` .gitignore at all though

2024-06-06 07:12 UTC, LunarX commented on rich-html-editor/build.gradle.kts
> +        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
Good call, I removed it alongside every test library

2024-06-06 08:15 UTC, tevincent commented on sample/.gitignore
> +/build
Maybe. I was asking that because maybe we need to ensure we have the right gitignore. But if you're sure, you can resolve that thread.

2024-06-06 14:47 UTC, sirambd approved these changes

2024-06-10 06:32 UTC, tevincent approved these changes

2024-06-10 06:50 UTC, merged