Support ordered and unordered lists
Infomaniak/android-rich-html-editor pull request #10
Opened 2024-06-11 12:14 UTC by LunarX

Depends on #9

2024-06-12 09:24 UTC, KevinBoulongne requested changes

2024-06-12 09:24 UTC, KevinBoulongne commented on rich-html-editor/src/main/assets/define_listeners.js
> +            newSelectionState["insertUnorderedList"]
```suggestion
            newSelectionState["insertUnorderedList"],
```

2024-06-13 09:01 UTC, LunarX commented on rich-html-editor/src/main/assets/define_listeners.js
> +            newSelectionState["insertUnorderedList"]
Yeah I knew it would bother you, unfortunately JS doesn't allow this :/

2024-06-17 04:37 UTC, KevinBoulongne commented on rich-html-editor/src/main/assets/define_listeners.js
> +            newSelectionState["insertUnorderedList"]
SHAME 💔

2024-06-19 11:59 UTC, KevinBoulongne approved these changes

2024-06-20 11:48 UTC, merged