Make toolbar visibly scrollable
Infomaniak/android-rich-html-editor pull request #12
Opened 2024-06-11 13:30 UTC by LunarX

Review while hiding white spaces in the diff

Depends on #11

2024-06-12 09:22 UTC, KevinBoulongne requested changes

2024-06-12 09:22 UTC, KevinBoulongne commented on sample/src/main/res/layout/fragment_editor_sample.xml
> +        android:padding="8dp"
No dimens for padding ?

2024-06-13 09:11 UTC, LunarX commented on sample/src/main/res/layout/fragment_editor_sample.xml
> +        android:padding="8dp"
Yeah for a small single fragment sample project like this one I figured this would be quicker to do it this way. What's your opinion on it?

2024-06-19 11:57 UTC, KevinBoulongne commented on sample/src/main/res/layout/fragment_editor_sample.xml
> +        android:padding="8dp"
Oh it's in the sample, my bad.

2024-06-19 11:58 UTC, KevinBoulongne approved these changes

2024-06-20 11:52 UTC, merged