Save edited HTML on configuration changed
Infomaniak/android-rich-html-editor pull request #15
Opened 2024-06-14 12:43 UTC by LunarX

When the html is edited by the user, we need to keep the changes and reload the edited html across config changes

Depends on #14

2024-06-18 13:46 UTC, sirambd requested changes

2024-06-18 13:46 UTC, sirambd commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorReloader.kt
Missing kDoc here

2024-06-18 13:46 UTC, sirambd commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorReloader.kt
> +class EditorReloader(private val viewModelScope: CoroutineScope) {
```suggestion
class EditorReloader(private val coroutineScope: CoroutineScope) {
```

2024-06-18 13:46 UTC, sirambd commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorReloader.kt
> +            savedHtml.collect {
`collectLatest` is better

2024-06-18 13:46 UTC, sirambd commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorReloader.kt
> +        if (needToReloadHtml) {
Check if it's main thread and throw if needed

2024-06-18 14:47 UTC, sirambd requested changes

2024-06-18 14:47 UTC, sirambd commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/EditorReloader.kt
> +        if (Looper.myLooper() != Looper.getMainLooper()) throw error("The load method needs to be called on the main thread")
The `error` method already uses throw, so there's no need to throw agin

2024-06-18 15:02 UTC, sirambd approved these changes

2024-06-19 12:05 UTC, KevinBoulongne approved these changes

2024-06-19 13:58 UTC, merged