Basic core functionalities and backbone code structure of the editor
Infomaniak/android-rich-html-editor pull request #2
Opened 2024-06-03 07:59 UTC by LunarX

This PR contains code that make a basic editor function properly but many details, polish and functionalities are still missing. I open this PR now because I feel like the core structure of the code is more stable than it ever was up to this point. Opening PRs before would have required to review code that would quickly end up being replaced which would have been a waste of time.

This PR contains:
* Main structure of the code
* An up to date sample project with every already present functionalities
* TODOs
* A lot of JS
* My sweat and tears

This PR does not contain:
* All functionalities of the editor
* All the library's KDoc
* All the logic to integrate seamlessly the editor inside the mail app
* Image/emoji support
* On configuration changed handling
* Catching and reporting JS errors
* A version of the editor for Jetpack Compose
* Metalava
* A correct proguard file
* Settings for jitpack to build the library without any issues
* A well redacted README.md
* The key to happiness
* Icons in the settings. (It doesn't even have settings altogether to begin with)

2024-06-03 12:24 UTC, valentinperignon commented on rich-html-editor/src/main/assets/link_detection.js
> +        target == DOCUMENT_POSITION_SAME ? position == DOCUMENT_POSITION_SAME : (position & target) == target
You can use strict equality

2024-06-04 12:02 UTC, tevincent commented
Sonar is not running on that project. Is that normal?

2024-06-06 11:26 UTC, LunarX commented
Sonar should run once the main branch has code merged into it apprently

2024-06-07 05:09 UTC, KevinBoulongne requested changes

2024-06-07 06:35 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/JsExecutableMethod.kt
> +    private val callbacks: MutableList<(String) -> Unit> = callback?.let { mutableListOf(it) } ?: mutableListOf()
Looks like it can't be written as a reference

2024-06-07 07:06 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/executor/JsExecutableMethod.kt
> +            }
After discussing, we agreed to keep the old one

2024-06-12 09:18 UTC, KevinBoulongne requested changes

2024-06-12 09:18 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/DocumentInitializer.kt
> +package com.infomaniak.lib.richhtmleditor
No copyright in this project ?

2024-06-12 09:30 UTC, KevinBoulongne requested changes

2024-06-12 09:30 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +            startsWith("rgba(") -> 5
Magic values.

2024-06-12 09:30 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
> +                (bottom * density).roundToInt()
```suggestion
                (bottom * density).roundToInt(),
```

2024-06-12 09:30 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/StatusCommand.kt
> +
```suggestion
```

2024-06-18 12:26 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/DocumentInitializer.kt
> +package com.infomaniak.lib.richhtmleditor
Once this PR is merged, we can easily merge all of the remaining PRs that depend on this one and it will probably be easier to include the copyright at this point. Anyway that observation is correct

2024-06-19 08:29 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +            startsWith("rgba(") -> 5
I actually changed the way I computed this part because I don't really need to do this two `startsWith` at all and this would also help me be more robust in my coding

2024-06-19 11:43 UTC, KevinBoulongne requested changes

2024-06-19 11:43 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/DocumentInitializer.kt
> +        evaluateJavascript("""document.getElementById("editor").innerHTML = `${html}`""", null)
The `editor` word should probably be in a variable somewhere, no ?

2024-06-19 11:43 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    }
```suggestion
    ) = coroutineScope.launch(defaultDispatcher) {
        editorStatuses.updateStatusesAtomically(
            isBold,
            isItalic,
            isStrikeThrough,
            isUnderlined,
            fontName,
            fontSize.toFloatOrNull(),
            textColor.toColorIntOrNull(),
            backgroundColor.toColorIntOrNull(),
            isLinkSelected,
        )
        _editorStatusesFlow.emit(editorStatuses)
    }
```

2024-06-19 11:43 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    }
```suggestion
    fun reportNewDocumentHeight(newHeight: Int) = coroutineScope.launch(mainDispatcher) {
        updateWebViewHeight(newHeight)
    }
```

2024-06-19 11:45 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/DocumentInitializer.kt
> +        evaluateJavascript("""document.getElementById("editor").innerHTML = `${html}`""", null)
Unfortunately it's used across, .html, .js and .kt files. I don't know if there's a truly robust and worth it solution to share something like this with everyone.

2024-06-19 12:08 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/DocumentInitializer.kt
> +        evaluateJavascript("""document.getElementById("editor").innerHTML = `${html}`""", null)
The string is extracted to its own const with a comment to try and find back every usage of the constant

2024-06-19 12:17 UTC, sirambd requested changes

2024-06-19 12:18 UTC, sirambd commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    }
The `launch` method returns a `Job`, and doing so risks returning this job which is useless to return.
We avoid returning things we don't need. We need a `Unit` return here

2024-06-19 12:21 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    }
@LunarX Is it part of the public API of the library ?

If yes, you can ignore this suggestion, because we probably don't want to expose the job to the user.
If no, that's the behavior we are always doing.

2024-06-19 12:28 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    }
It's not part of the public API, no

2024-06-19 12:33 UTC, sirambd commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    }
Even if it's not exposed, we'll do it as a best practice, so it'll be automatic all the time, returning only when necessary, otherwise `Unit`.
But here we can't use `Unit` with your proposal @KevinBoulongne

2024-06-19 12:34 UTC, KevinBoulongne approved these changes

2024-06-19 12:54 UTC, valentinperignon approved these changes

2024-06-19 12:56 UTC, merged