Adds a placeholder when the editor is empty
Infomaniak/android-rich-html-editor pull request #28
Opened 2024-07-10 13:31 UTC by LunarX

Adds a way to know if the editor is empty or not and be notified about it to display a placeholder

2024-07-16 08:41 UTC, KevinBoulongne requested changes

2024-07-16 08:41 UTC, KevinBoulongne commented on rich-html-editor/src/main/assets/attach_listeners.js
> +onEditorChildListChange(() => {
```suggestion
reportEmptyBodyStatus()

onEditorChildListChange(() => {
```

2024-07-17 12:33 UTC, LunarX commented on rich-html-editor/src/main/assets/attach_listeners.js
> +onEditorChildListChange(() => {
I feel like it kind of goes together and is best written like this. Like this onEditorChildListChange listeneris the part that will handle reporting empty body statues forever but we just want to report a first one as fast as possible as well

2024-07-18 06:58 UTC, tevincent approved these changes

2024-07-19 04:25 UTC, KevinBoulongne approved these changes

2024-07-19 06:24 UTC, merged