Add font size customization
Infomaniak/android-rich-html-editor pull request #9
Opened 2024-06-11 10:38 UTC by LunarX

Depends on #3

2024-06-12 09:21 UTC, KevinBoulongne requested changes

2024-06-12 09:21 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    fun setFontSize(@IntRange(from = 1, to = 7) fontSize: Int) = execCommand(StatusCommand.FONT_SIZE, fontSize)
Magic numbers.

2024-06-12 09:21 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
> +
```suggestion
```

2024-06-12 09:21 UTC, KevinBoulongne commented on sample/src/main/java/com/infomaniak/lib/richhtmleditor/sample/EditorSampleFragment.kt
> +        fontBigButton.setOnClickListener { editor.setFontSize(6) }
Magic numbers.

2024-06-13 08:25 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
> +
How did this end up here? Thanks

2024-06-13 08:52 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    fun setFontSize(@IntRange(from = 1, to = 7) fontSize: Int) = execCommand(StatusCommand.FONT_SIZE, fontSize)
Is it truly worth the effort to extract these values into constants and have to manage them for a simple `@IntRange`? For other parts of the code, I agree, but the IntRange I'm not so sure

2024-06-19 11:53 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/JsBridge.kt
> +    fun setFontSize(@IntRange(from = 1, to = 7) fontSize: Int) = execCommand(StatusCommand.FONT_SIZE, fontSize)
At least a comment to explain what are 1 & 7 ?

1 what ? 1 px ? 1 dp ? 1 size ?
7 what ?
Why only 1 to 7 ?
What is the meaning of life ?

2024-06-19 11:54 UTC, KevinBoulongne requested changes

2024-06-19 11:54 UTC, KevinBoulongne commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
> +    fun setFontSize(@IntRange(from = 1, to = 7) fontSize: Int) = jsBridge.setFontSize(fontSize)
Same magic numbers, and now they are duplicated.

2024-06-19 14:46 UTC, LunarX commented on rich-html-editor/src/main/java/com/infomaniak/lib/richhtmleditor/RichHtmlEditorWebView.kt
> +    fun setFontSize(@IntRange(from = 1, to = 7) fontSize: Int) = jsBridge.setFontSize(fontSize)
In the end you were not the only one who wanted to extract it anyway, so I did

2024-06-20 11:42 UTC, KevinBoulongne approved these changes

2024-06-20 11:46 UTC, merged